version: "3.7"

services:
  vault:
    image: vault
    container_name: vault
    networks:
      - default
      - proxy
    volumes:
      - vault:/vault
      - /etc/vault/config.hcl:/vault/config/config.hcl
      - caddy:/caddy
    ports:
      - 8200
    cap_add:
      - IPC_LOCK
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    command: ["server"]

volumes:
  vault:
  caddy:
    external: true
networks:
  proxy:
    external: true
